zenstruck_messenger_monitor:
    storage:
        orm:
            entity_class: App\Entity\ProcessedMessage
        exclude:
            - App\Message\DriverLocationUpdatedMessage
            - App\Message\DetectGpsAnomalyMessage
