---
# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
  database:
    command:
      - --default-authentication-plugin=mysql_native_password
      - --transaction-isolation=READ-COMMITTED
      - --innodb_rollback_on_timeout=ON
