---
# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    volumes:
      - jwt_data:/app/config/jwt:rw,cached
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
  database:
    command:
      - --transaction-isolation=READ-COMMITTED
      - --innodb_rollback_on_timeout=ON

volumes:
  jwt_data:
