<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260402004432 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE push_devices (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, expo_push_token VARCHAR(255) NOT NULL, platform VARCHAR(10) NOT NULL, device_name VARCHAR(255) DEFAULT NULL, os_version VARCHAR(20) DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_push_devices_user_id ON push_devices (user_id)');
        $this->addSql('CREATE INDEX idx_push_devices_active ON push_devices (is_active)');
        $this->addSql('CREATE UNIQUE INDEX uniq_expo_token ON push_devices (expo_push_token)');
        $this->addSql('CREATE TABLE push_tickets (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ticket_id VARCHAR(255) NOT NULL, expo_push_token VARCHAR(255) NOT NULL, notification_type VARCHAR(50) NOT NULL, status VARCHAR(20) NOT NULL, error_details JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, checked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_push_tickets_status_created ON push_tickets (status, created_at)');
        $this->addSql('ALTER TABLE push_devices ADD CONSTRAINT FK_2A42D483A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE push_devices DROP CONSTRAINT FK_2A42D483A76ED395');
        $this->addSql('DROP TABLE push_devices');
        $this->addSql('DROP TABLE push_tickets');
    }
}
